# Purpose: to learn from dataset: https://www.kaggle.com/datasets/razanihababdellatif/nyc-regents-exam-dataset/data

1. Import Libraries

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import AutoClean as ac

2. Load the Dataset

In [6]:
df = pd.read_csv('2014-15_to_2017-19_NYC_Regents_Exam_Results_-_Public_20260724.csv')
df

C:\Users\jc\AppData\Local\Temp\ipykernel_32792\410813979.py:1: DtypeWarning: Columns (0: Total Tested) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('2014-15_to_2017-19_NYC_Regents_Exam_Results_-_Public_20260724.csv')

,Unnamed Column,School DBN,School Name,School Type,School Level,Regents Exam,Year,Category,Total Tested,Mean Score,Number Scoring Below 65,Percent Scoring Below 65,Number Scoring 65 or Above,Percent Scoring 65 or Above,Number Scoring 80 or Above,Percent Scoring 80 or Above,Number Scoring CR,Percent Scoring CR
0,08X5072015All StudentsGeometry,08X507,Stevenson Yabc,YABC,High school,Geometry,2015,All Students,1,s,s,s,s,s,s,s,s,s
1,01M1842018All StudentsLiving Environment,01M184,P.S. 184m Shuang Wen,General Academic,K-8,Living Environment,2018,All Students,32,90.2,0,0.0,32,100.0,31,96.9,na,na
2,01M4582019All StudentsSpanish,01M458,Forsyth Satellite Academy,Transfer School,High school,Spanish,2019,All Students,1,s,s,s,s,s,s,s,s,s
3,01M5092017All StudentsSpanish,01M509,Marta Valle High School,General Academic,High school,Spanish,2017,All Students,16,82.7,0,0.0,16,100.0,10,62.5,na,na
4,02M2982015All StudentsGeometry,02M298,Pace High School,General Academic,High school,Geometry,2015,All Students,163,62.9,81,49.7,82,50.3,13,8.0,13,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33026,84X7172017All StudentsLiving Environment,84X717,Icahn Charter School,General Academic,K-8,Living Environment,2017,All Students,10,79.7,0,0.0,10,100.0,5,50.0,na,na
33027,84X7172018All StudentsCommon Core Algebra,84X717,Icahn Charter School,General Academic,K-8,Common Core Algebra,2018,All Students,15,86.9,0,0.0,15,100.0,15,100.0,15,100.0
33028,84X7172018All StudentsLiving Environment,84X717,Icahn Charter School,General Academic,K-8,Living Environment,2018,All Students,9,85.3,0,0.0,9,100.0,8,88.9,na,na
33029,84X7172019All StudentsCommon Core Algebra,84X717,Icahn Charter School,General Academic,K-8,Common Core Algebra,2019,All Students,15,93.2,0,0.0,15,100.0,15,100.0,15,100.0
33030,84X7172019All StudentsLiving Environment,84X717,Icahn Charter School,General Academic,K-8,Living Environment,2019,All Students,14,77.9,0,0.0,14,100.0,8,57.1,na,na

In [8]:
df.shape

(33031, 18)

In [9]:
df.info()
df.dtypes
df.isna().sum()

<class 'pandas.DataFrame'>
RangeIndex: 33031 entries, 0 to 33030
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Unnamed Column               33031 non-null  str
 1   School DBN                   33031 non-null  str
 2   School Name                  33031 non-null  str
 3   School Type                  33031 non-null  str
 4   School Level                 33031 non-null  str
 5   Regents Exam                 33031 non-null  str
 6   Year                         33031 non-null  int64
 7   Category                     33031 non-null  str
 8   Total Tested                 33031 non-null  object
 9   Mean Score                   33031 non-null  str
 10  Number Scoring Below 65      33031 non-null  str
 11  Percent Scoring Below 65     33031 non-null  str
 12  Number Scoring 65 or Above   33031 non-null  str
 13  Percent Scoring 65 or Above  33031 non-null  str
 14  Number Scoring 80 or Above   33031 non-null  str
 15  Percent Scoring 80 or Above  33031 non-null  str
 16  Number Scoring CR            33031 non-null  str
 17  Percent Scoring CR           33031 non-null  str
dtypes: int64(1), object(1), str(16)
memory usage: 9.8+ MB

Unnamed Column                 0
School DBN                     0
School Name                    0
School Type                    0
School Level                   0
Regents Exam                   0
Year                           0
Category                       0
Total Tested                   0
Mean Score                     0
Number Scoring Below 65        0
Percent Scoring Below 65       0
Number Scoring 65 or Above     0
Percent Scoring 65 or Above    0
Number Scoring 80 or Above     0
Percent Scoring 80 or Above    0
Number Scoring CR              0
Percent Scoring CR             0
dtype: int64

In [ ]:
# How many rows are suppressed ('s') in our target column?
print(df['Percent Scoring 65 or Above'].value_counts().head())
print("\nSuppressed rows:", (df['Percent Scoring 65 or Above'] == 's').sum())

Percent Scoring 65 or Above
s        3531
100.0    2197
0.0       439
50.0      330
33.3      251
Name: count, dtype: int64

Suppressed rows: 3531

In [47]:
# Run AutoClean to clean the data
cleaning_pipeline = ac.AutoClean(df)
df_clean = cleaning_pipeline.output
df_clean

AutoClean process completed in 0.092081 seconds
Logfile saved to: c:\Users\jc\Documents\GitHub\kaggle_learn\NYC Regents Exam\autoclean.log

,Unnamed Column,School DBN,School Name,School Type,School Level,Regents Exam,Year,Category,Total Tested,Mean Score,...,School Level_Junior High-Intermediate-Middle,School Level_K-12 all grades,School Level_K-8,School Level_Secondary School,School Level_Ungraded,School Type_Career Technical,School Type_General Academic,School Type_Special Education,School Type_Transfer School,School Type_YABC
0,08X5072015All StudentsGeometry,08X507,Stevenson Yabc,YABC,High school,Geometry,2015,All Students,1,s,...,False,False,False,False,False,False,False,False,False,True
1,01M1842018All StudentsLiving Environment,01M184,P.S. 184m Shuang Wen,General Academic,K-8,Living Environment,2018,All Students,32,90.2,...,False,False,True,False,False,False,True,False,False,False
2,01M4582019All StudentsSpanish,01M458,Forsyth Satellite Academy,Transfer School,High school,Spanish,2019,All Students,1,s,...,False,False,False,False,False,False,False,False,True,False
3,01M5092017All StudentsSpanish,01M509,Marta Valle High School,General Academic,High school,Spanish,2017,All Students,16,82.7,...,False,False,False,False,False,False,True,False,False,False
4,02M2982015All StudentsGeometry,02M298,Pace High School,General Academic,High school,Geometry,2015,All Students,163,62.9,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33026,84X7172017All StudentsLiving Environment,84X717,Icahn Charter School,General Academic,K-8,Living Environment,2017,All Students,10,79.7,...,False,False,True,False,False,False,True,False,False,False
33027,84X7172018All StudentsCommon Core Algebra,84X717,Icahn Charter School,General Academic,K-8,Common Core Algebra,2018,All Students,15,86.9,...,False,False,True,False,False,False,True,False,False,False
33028,84X7172018All StudentsLiving Environment,84X717,Icahn Charter School,General Academic,K-8,Living Environment,2018,All Students,9,85.3,...,False,False,True,False,False,False,True,False,False,False
33029,84X7172019All StudentsCommon Core Algebra,84X717,Icahn Charter School,General Academic,K-8,Common Core Algebra,2019,All Students,15,93.2,...,False,False,True,False,False,False,True,False,False,False
33030,84X7172019All StudentsLiving Environment,84X717,Icahn Charter School,General Academic,K-8,Living Environment,2019,All Students,14,77.9,...,False,False,True,False,False,False,True,False,False,False

In [51]:
df_clean.shape
df_clean.columns
df_clean.head(10)
df_clean['Percent Scoring 65 or Above']

0            s
1        100.0
2            s
3        100.0
4         50.3
         ...
33026    100.0
33027    100.0
33028    100.0
33029    100.0
33030    100.0
Name: Percent Scoring 65 or Above, Length: 33031, dtype: str

In [52]:
# Eliminate rows with suppressed values in the target column
df_clean = df_clean[df_clean['Percent Scoring 65 or Above'] != 's']
df_clean["Percent Scoring 65 or Above"] = df_clean["Percent Scoring 65 or Above"].astype("float")

# Create a target column called "Pass_Target" that is 1 if the student passed (scored 65 or above) and 0 if they failed (scored below 65)
df_clean['Pass_Target'] = (df_clean['Percent Scoring 65 or Above'] >= 65).astype(int)
df_clean

,Unnamed Column,School DBN,School Name,School Type,School Level,Regents Exam,Year,Category,Total Tested,Mean Score,...,School Level_K-12 all grades,School Level_K-8,School Level_Secondary School,School Level_Ungraded,School Type_Career Technical,School Type_General Academic,School Type_Special Education,School Type_Transfer School,School Type_YABC,Pass_Target
1,01M1842018All StudentsLiving Environment,01M184,P.S. 184m Shuang Wen,General Academic,K-8,Living Environment,2018,All Students,32,90.2,...,False,True,False,False,False,True,False,False,False,1
3,01M5092017All StudentsSpanish,01M509,Marta Valle High School,General Academic,High school,Spanish,2017,All Students,16,82.7,...,False,False,False,False,False,True,False,False,False,1
4,02M2982015All StudentsGeometry,02M298,Pace High School,General Academic,High school,Geometry,2015,All Students,163,62.9,...,False,False,False,False,False,True,False,False,False,0
7,02M4002019All StudentsFrench,02M400,High School for Environmental Studies,General Academic,High school,French,2019,All Students,21,81.5,...,False,False,False,False,False,True,False,False,False,1
8,02M4142015All StudentsEnglish,02M414,N.Y.C. Museum School,General Academic,High school,English,2015,All Students,128,87.4,...,False,False,False,False,False,True,False,False,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33026,84X7172017All StudentsLiving Environment,84X717,Icahn Charter School,General Academic,K-8,Living Environment,2017,All Students,10,79.7,...,False,True,False,False,False,True,False,False,False,1
33027,84X7172018All StudentsCommon Core Algebra,84X717,Icahn Charter School,General Academic,K-8,Common Core Algebra,2018,All Students,15,86.9,...,False,True,False,False,False,True,False,False,False,1
33028,84X7172018All StudentsLiving Environment,84X717,Icahn Charter School,General Academic,K-8,Living Environment,2018,All Students,9,85.3,...,False,True,False,False,False,True,False,False,False,1
33029,84X7172019All StudentsCommon Core Algebra,84X717,Icahn Charter School,General Academic,K-8,Common Core Algebra,2019,All Students,15,93.2,...,False,True,False,False,False,True,False,False,False,1
33030,84X7172019All StudentsLiving Environment,84X717,Icahn Charter School,General Academic,K-8,Living Environment,2019,All Students,14,77.9,...,False,True,False,False,False,True,False,False,False,1